import type { Metadata } from "next";
import { Lobster } from "next/font/google";
import "./ui/globals.css";
import Link from "next/link";
import { Providers } from "./providers";
const lobster = Lobster({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={lobster.className}>
        <Providers>
          <nav className=" text-white bg-slate-600">
            <div className="container mx-auto p-4">
              <Link href={"/"}>Home</Link>
            </div>
          </nav>
          <div className="container mx-auto p-4 tracking-widest">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
